// Type will be generated by Convex, using a conditional import
type ConvexId = string;

export interface GearItem {
  _id: ConvexId;
  name: string;
  group: string;
  type: 'tent' | 'hotel' | 'all';
  amount: number;
}
export interface GearItemToPack extends Omit<GearItem, '_id'> {
  _id?: ConvexId;
  packed: boolean;
}

export type GearList = GearItem[];

export interface GroupedGearList {
  [group: string]: GearList;
}

export interface GroupedGearListToPack {
  [group: string]: GearItemToPack[];
}

const groupAndMarkList = (gearList: GearItem[]): GroupedGearListToPack => {
  const listWithPackedInfo: GearItemToPack[] = gearList.map((item) => ({
    ...item,
    packed: false,
  }));
  return listWithPackedInfo.reduce((acc: GroupedGearListToPack, item) => {
    return {
      ...acc,
      [item.group]: [...(acc[item.group] ?? []), item],
    };
  }, {});
};

export { groupAndMarkList };
